In [3]:
import numpy as np
np.random.seed(42)

In [4]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD  #stochastic gradient descent

Using TensorFlow backend.


In [22]:
(x_train, y_train), (x_test, y_test) = mnist.load_data()  

In [23]:
x_train.shape  #60000 digit images of size 28 by 28 of grey scale

(60000, 28, 28)

In [24]:
y_train.shape #60,000 classifiers/labels for each image/data

(60000,)

In [25]:
y_train[0:20] #first 20 labels associated with digit images

array([5, 0, 4, 1, 9, 2, 1, 3, 1, 4, 3, 5, 3, 6, 1, 7, 2, 8, 6, 9],
      dtype=uint8)

In [26]:
x_test.shape #10,000 images for test

(10000, 28, 28)

In [13]:
x_test[0] #first pixel image - not binary ; (0-254 pixel representation)

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [27]:
y_test[0]  #actual image label

7

In [28]:
x_trainb = x_train.reshape(60000, 784).astype('float32') #convert into vector ; 28*28 = 784 and float type
x_testb = x_test.reshape(10000, 784).astype('float32')


In [29]:
x_trainb /= 255  # convert images in binary format; 0 or 1 pixel rep
x_testb /= 255
x_testb[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [30]:
n_classes=10
y_train = keras.utils.to_categorical(y_train, n_classes) # associate 0-9 categories, that converts a number to 10 binary digits indicating number one out of ten.
y_test = keras.utils.to_categorical(y_test, n_classes)
y_test[0]

array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)

In [32]:
model = Sequential()
model.add(Dense(64, activation='sigmoid', input_shape=(784,)))   #input layer; 64 hyperparam = 64 neurons; 
model.add(Dense(10, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


In [34]:
model.summary()   #50240 possibilities; (64 * 784)+ 64 weights gor each neuron  ;; 650 = (10*64)+10

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 64)                50240     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                650       
Total params: 50,890
Trainable params: 50,890
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(loss="mean_squared_error", optimizer=SGD(lr=0.01), metrics=['accuracy'])

In [39]:
model.fit(x_trainb, y_train, batch_size=128, epochs=50, verbose=1, validation_data=(x_testb, y_test)) # train the model with running 50 iterations and batch size 128 and not all data

Train on 60000 samples, validate on 10000 samples
Epoch 1/50
60000/60000 [==============================] - 1s 12us/step - loss: 0.0703 - acc: 0.5468 - val_loss: 0.0698 - val_acc: 0.5556
Epoch 2/50
60000/60000 [==============================] - 1s 13us/step - loss: 0.0698 - acc: 0.5540 - val_loss: 0.0693 - val_acc: 0.5623
Epoch 3/50
60000/60000 [==============================] - 1s 11us/step - loss: 0.0694 - acc: 0.5605 - val_loss: 0.0689 - val_acc: 0.5679
Epoch 4/50
60000/60000 [==============================] - 1s 11us/step - loss: 0.0689 - acc: 0.5670 - val_loss: 0.0684 - val_acc: 0.5739
Epoch 5/50
60000/60000 [==============================] - 1s 11us/step - loss: 0.0684 - acc: 0.5730 - val_loss: 0.0679 - val_acc: 0.5785
Epoch 6/50
60000/60000 [==============================] - 1s 11us/step - loss: 0.0680 - acc: 0.5782 - val_loss: 0.0674 - val_acc: 0.5836
Epoch 7/50
60000/60000 [==============================] - 1s 11us/step - loss: 0.0675 - acc: 0.5832 - val_loss: 0.0670 - val_acc

In [42]:
model.evaluate(x_testb, y_test)

10000/10000 [==============================] - 0s 18us/step


[0.04846748489737511, 0.7292]